shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3

packages:
  - playground
  - docs
overrides:
  magic-regexp: 'link:.'
  nuxt: 4.3.1
  vite: 7.3.1
  vue: 3.5.29

allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': true
  esbuild: false
  shadcn-docs-nuxt: false
  sharp: true
  simple-git-hooks: true
  unrs-resolver: false
  vue-demi: false
