name: "\U0001F4DA Documentation"
description: How do I ... ?
title: "docs: "
labels: ["documentation"]
assignees: danielroe
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: 📚 Is your documentation request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I feel I should be able to [...] but I can't see how to do it from the docs.
  - type: textarea
    attributes:
      label: 🔍 Where should you find it?
      description: What page of the docs do you expect this information to be found on?
  - type: textarea
    attributes:
      label: ℹ️ Additional context
      description: Add any other context or information.
